import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/footer/Footer";
import Navbar from "@/components/shared/navbar/Navbar";
//import Banner from "@/components/shared/banner/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tiles Gallery App",
  description: "Generated by create Tiles Gallery app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
      <Navbar/>
      <main className='max-w-300 mx-auto'>
        {/* <Banner/> */}
        {children}
        <ToastContainer position="top-center"/>
      </main>
      <Footer/>
      </body>
    </html>
  );
}
